/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  openApiSidebar: [
    {
      type: "category",
      label: "API Sandbox",
      link: {
        type: "generated-index",
        title: "Andreani API Sandbox",
        description: "Andreani API Sandbox documentación",
        slug: "/category/andreani"
      },
      // @ts-ignore
      items: require("./docs/andreani/sidebar.js")
    }
  ]
  /* openApiSidebar: [
    {
      // @ts-ignore
      type: "category",
      // @ts-ignore
      label: "Petstore",
      link: {
        // @ts-ignore
        type: "generated-index",
        // @ts-ignore
        title: "Petstore API",
        // @ts-ignore
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        // @ts-ignore
        slug: "/category/petstore-api"
      },
      // @ts-ignore
      items: require("./docs/petstore/sidebar.js")
    },
  ], */
};

module.exports = sidebars;
