openapi: 3.0.0
info:
  title: API de logística de pedidos
  version: 1.0.0
  description: API para gestionar pedidos de una empresa de logística
servers:
  - url: http://localhost:3000
paths:
  /orden/{numeroOrden}:
    get:
      summary: Obtener información de un pedido
      parameters:
        - in: path
          name: numeroOrden
          schema:
            type: string
          required: true
          description: El número de orden del pedido que se quiere obtener
      responses:
        '200':
          description: Información del pedido solicitado
          content:
            application/json:
              schema:
                type: object
                properties:
                  numeroOrden:
                    type: string
                    description: El número de orden del pedido
                  fechaPedido:
                    type: string
                    format: date
                    description: La fecha en la que se hizo el pedido
                  cliente:
                    type: object
                    properties:
                      nombre:
                        type: string
                        description: El nombre del cliente
                      direccion:
                        type: string
                        description: La dirección del cliente
                  productos:
                    type: array
                    items:
                      type: object
                      properties:
                        nombre:
                          type: string
                          description: El nombre del producto
                        cantidad:
                          type: integer
                          description: La cantidad del producto
        '403':
          description: No se ha autenticado correctamente
        '404':
          description: No se ha encontrado la orden solicitada
        '500':
          description: Error interno del servidor
    post:
      summary: Generar una nueva orden de envío
      requestBody:
        description: Información de la nueva orden de envío
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numeroOrden:
                  type: string
                  description: El número de orden del pedido
                fechaPedido:
                  type: string
                  format: date
                  description: La fecha en la que se hizo el pedido
                cliente:
                  type: object
                  properties:
                    nombre:
                      type: string
                      description: El nombre del cliente
                    direccion:
                      type: string
                      description: La dirección del cliente
                productos:
                  type: array
                  items:
                    type: object
                    properties:
                      nombre:
                        type: string
                        description: El nombre del producto
                      cantidad:
                        type: integer
                        description: La cantidad del producto
      responses:
        '200':
          description: La orden de envío se ha creado correctamente
        '403':
          description: No se ha autenticado correctamente
        '500':
          description: Error interno del servidor

