openapi: 3.0.0
info:
  title: Datos de Facturación API
  version: 1.0.0
  description: Microservicio para gestionar los datos de facturación de los clientes.
servers:
  - url: https://api-datos-facturacion-v2-equipo-almacenes-test.apps.ocptest.andreani.com.ar
paths:
  /facturacion/clientes:
    get:
      summary: Obtiene la lista de todos los clientes para facturación.
      operationId: getClientesFacturacion
      responses:
        '200':
          description: Lista de clientes para facturación.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteFacturacion'
    post:
      summary: Crea un nuevo cliente para facturación.
      operationId: crearClienteFacturacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NuevoClienteFacturacion'
      responses:
        '201':
          description: Cliente creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteFacturacion'
  /facturacion/clientes/{id}:
    get:
      summary: Obtiene el detalle de un cliente específico para facturación.
      operationId: getClienteFacturacionById
      parameters:
        - name: id
          in: path
          description: Identificador del cliente a obtener.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Cliente encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteFacturacion'
        '404':
          description: Cliente no encontrado.
    put:
      summary: Actualiza los datos de un cliente específico para facturación.
      operationId: actualizarClienteFacturacion
      parameters:
        - name: id
          in: path
          description: Identificador del cliente a actualizar.
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NuevoClienteFacturacion'
      responses:
        '200':
          description: Cliente actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteFacturacion'
        '404':
          description: Cliente no encontrado.
    delete:
      summary: Elimina un cliente específico para facturación.
      operationId: eliminarClienteFacturacion
      parameters:
        - name: id
          in: path
          description: Identificador del cliente a eliminar.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: Cliente eliminado exitosamente.
        '404':
          description: Cliente no encontrado.
components:
  schemas:
    ClienteFacturacion:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        cuit:
          type: string
      required:
        - id
        - nombre
        - cuit
    NuevoClienteFacturacion:
      type: object