openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Especificación de API de Pedidos"
  description: "API para la gestión de pedidos de almacenes"
servers:
  - url: "https://api-pedidos-almacenes-v2-equipo-almacenes-test.apps.ocptest.andreani.com.ar"
paths:
  /almacenes/pedidos/{id}:
    get:
      summary: "Obtiene el detalle de un pedido específico"
      parameters:
        - in: path
          name: id
          description: "ID del pedido a obtener"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Detalle del pedido obtenido exitosamente"
    put:
      summary: "Actualiza los datos de un pedido específico"
      parameters:
        - in: path
          name: id
          description: "ID del pedido a actualizar"
          required: true
          schema:
            type: integer
      requestBody:
        description: "Datos actualizados del pedido"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pedido"
      responses:
        '200':
          description: "Pedido actualizado exitosamente"
components:
  schemas:
    Pedido:
      type: object
      properties:
        id:
          type: integer
        cliente:
          type: string
        fecha:
          type: string
        estado:
          type: string
